### ISSUE TITLE
Do you plan to write FPU for River CPU?

### ISSUE THREAD

**Issue by hyf6661669** [sergeykhbr/riscv_vhdl#23]
Your work is very amazing. Since I find it really hard to understand Chisel codes for Rocket-chip, your work helps me a lot on studying the CPU design. Have you considered designing a single/double-precision FPU? The FPU used by Rocket-chip is also written in Chisel and the developers don't write any documents about it. So it's also difficult to understand.

**Comment by sergeykhbr** [comment]
Hi,
I have a long list of what could be done and improved and FPU is on the second or third place in the list. There're also such things as: I/D caches, independent debug bus interface with the watchpoints, triggers and trace capabilities, MMU and other things. But I cannot say when and what will be done because it is a free-time project.

Thank you for your interest.
